export const ActionTypes = {
  FETCH_RESTAURANT: 'FETCH_RESTAURANT',
  FETCH_ITEM: 'FETCH_ITEM',
  FETCH_ITEMS: 'FETCH_ITEMS',
  LOGINUSERS: 'LOGINUSERS',
  REGISTERUSERS: "REGISTERUSERS",
  UPDATE_USERINFO:"UPDATE_USERINFO",
  ADDUSERINFO:"ADDUSERINFO,"
};
